# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'repUS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  # Pods for repUS

  target 'repUS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'repUSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'repUS-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for repUS-tvOS


end
